# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Maximiliano Saldaña
title: Senior Software Developer
email: maxi.sald@gmail.com
website: maxisaldana.github.io

# Social links
twitter_username: maxi_sald
github_username:  maxisaldana
# dribbble_username: jekyll
facebook_username: maxisald
# flickr_username: jekyll
instagram_username: maxi_sald
linkedin_username: maxisaldana
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  

  I am most skilled in: 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
